---

- name: Gather facts from minotar-cache
  hosts:
    - minotar-cache
  tasks: [ ]
  tags:
    - imgd
    - configuration

- name: Setup Minotar imgd Backend
  hosts: minotar-backend
  sudo: yes
  serial: 10
  vars_files:
    - redis_password.yml
    - group_vars/common
    - group_vars/backend

  roles:
    - common
    - backend
