---

- hosts: minotar-cache
  name: Gather facts from minotar-cache
  tasks: [ ]
  tags:
    - imgd
    - configuration

- name: Setup Minotar imgd Backend
  hosts: minotar-backend
  sudo: yes
  serial: 1
  vars_files:
    - redis_password.yml
    - group_vars/common
    - group_vars/backend

  roles:
    - common
    - backend
