---

- name: Gather facts from minotar-backend and minotar-cache
  hosts:
    - minotar-cache
    - minotar-backend
  tasks: [ ]
  tags:
    - configuration

- name: Setup Minotar Frontend Site and Accelerator
  hosts: minotar-frontend
  sudo: yes
  vars_files:
    - group_vars/common
    - group_vars/frontend

  roles:
    - common
    - frontend
