
- include: nginx.yml
- include: varnish.yml

- name: Create Web Directory
  file:
    path: /srv/www
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Set default deploy acls
  acl:
    name: /srv/www
    entity: staff
    etype: group
    permissions: "rwx"
    default: yes
    state: present

- name: Set deploy acls
  acl:
    name: /srv/www
    entity: staff
    etype: group
    permissions: "rwx"
    state: present

## Are these needed?

#- name: set default web acls
#  acl:
#    name: /srv/www
#    entity: nginx
#    etype: group
#    permissions: "rwx"
#    default: yes
#    state: present

#- name: set web acls
#  acl:
#    name: /srv/www
#    entity: nginx
#    etype: group
#    permissions: "rwx"
#    state: present

- include: projects.yml
