# Install software
- name: Install nginx
  yum: name=nginx state=present

- name: Enable nginx service
  service: name=nginx enabled=yes state=started

- name: Copy nginx config
  template: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: Create projects directory
  file: path=/srv/www state=directory

- name: create directories
  command: mkdir -p /srv/www creates=/srv/www

- name: set default deploy acls
  acl: name=/srv/www entity=staff etype=group permissions="rwx" default=yes state=present

- name: set deploy acls
  acl: name=/srv/www entity=staff etype=group permissions="rwx" state=present

- name: set default web acls
  acl: name=/srv/www entity=nginx etype=group permissions="rwx" default=yes state=present

- name: set web acls
  acl: name=/srv/www entity=nginx etype=group permissions="rwx" state=present

- include: projects.yml
