- name: Install nginx
  apt:
    name: nginx
    update_cache: yes
    cache_valid_time: 86400
    state: present

- name: Enable nginx at boot
  service:
    name: nginx
    enabled: yes
    state: stopped

- name: Write nginx configuration
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx
