---
- name: Checkout git repos
  git:
    repo: "{{ item.value.checkout.repo }}"
    dest: "{{ item.value.checkout.dest }}"
    accept_hostkey: yes
  with_dict: projects
  when: item.value.checkout is defined

- name: Fix permissions on directory
  file:
    path: "{{ item.value.root }}/logs"
    state: directory
    group: "{{ nginx_user }}"
    owner: "{{ nginx_user }}"
    mode: 0770
    recurse: yes
  with_dict: projects
  notify:
    - restart nginx