# Install software
- name: Install software
  apt: name=git,vim,wget state=present
  sudo: yes

- include: groups.yml
- include: users.yml

- name: Install staff sudoers
  template: src=30-dev dest=/etc/sudoers.d/30-dev
  sudo: yes
